export const items = [
    {
        id: 1,
        title: "Elegant Leather Watch",
        image: "/images/1.png",
        description: "A sophisticated leather watch for all occasions.",
        company: "Timepiece Creations",
        price: 99.99,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 2,
        title: "Cozy Knit Sweater",
        image: "/images/sweater.png",
        description: "Stay warm and stylish with this soft knit sweater.",
        company: "Fashion Forward",
        price: 49.95,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 3,
        title: "Vintage Polaroid Camera",
        image: "/images/3.png",
        description: "Capture moments in retro style with this classic camera.",
        company: "Nostalgia Co.",
        price: 129.0,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 4,
        title: "Modern Bluetooth Headphones",
        image: "/images/4.png",
        description:
            "Experience high-quality sound and comfort with these headphones.",
        company: "AudioTech",
        price: 79.99,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 5,
        title: "Luxury Fountain Pen",
        image: "/images/5.png",
        description: "Write with elegance using this exquisite fountain pen.",
        company: "Inkwell Designs",
        price: 149.5,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 6,
        title: "Sleek Laptop Backpack",
        image: "/images/6.png",
        description:
            "Carry your essentials in style with this modern laptop backpack.",
        company: "TechGear",
        price: 69.95,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 7,
        title: "Artistic Canvas Painting",
        image: "/images/m1air.png",
        description:
            "Add a touch of art to your home with this beautiful canvas painting.",
        company: "Artistic Expressions",
        price: 189.0,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 8,
        title: "Gourmet Coffee Beans",
        image: "/images/m1air.png",
        description:
            "Indulge in the rich flavors of these premium coffee beans.",
        company: "Bean Master",
        price: 12.99,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 9,
        title: "Classic Leather Wallet",
        image: "/images/m1air.png",
        description:
            "Keep your cards and cash organized with this timeless leather wallet.",
        company: "LeatherCraft",
        price: 45.0,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 10,
        title: "Minimalist Wristwatch",
        image: "/images/m1air.png",
        description:
            "A sleek and minimalistic wristwatch that complements any outfit.",
        company: "Timeless Watches",
        price: 89.95,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 11,
        title: "Deluxe Chef's Knife",
        image: "/images/m1air.png",
        description:
            "Upgrade your kitchen with this high-quality chef's knife.",
        company: "Culinary Masterpieces",
        price: 149.0,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 12,
        title: "Stylish Sunglasses",
        image: "/images/m1air.png",
        description:
            "Protect your eyes in style with these fashionable sunglasses.",
        company: "Sunshine Shades",
        price: 59.99,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 13,
        title: "Chic Leather Boots",
        image: "/images/m1air.png",
        description: "Step out in confidence with these trendy leather boots.",
        company: "Urban Chic",
        price: 129.95,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 14,
        title: "Aromatherapy Diffuser",
        image: "/images/m1air.png",
        description:
            "Create a soothing ambiance with this aromatherapy diffuser.",
        company: "Relaxation Station",
        price: 34.5,
        rateValue: 0,
        rateCount: 0,
    },
    {
        id: 15,
        title: "Portable Bluetooth Speaker",
        image: "/images/m1air.png",
        description:
            "Enjoy your favorite music on the go with this compact speaker.",
        company: "SoundWave",
        price: 59.95,
        rateValue: 0,
        rateCount: 0,
    },
];
